"""Entry point for puzzle_solver with SVG-based analysis."""

import cv2
from pathlib import Path
from puzzle_solver.solver import solve_puzzle
from puzzle_solver.common import InteractiveImageViewer


def run_solver(temp_folder_name: str = None,
               piece_id_1: int = None,
               piece_id_2: int = None,
               solver_algorithm: str = 'edge_v2',
               show_visualizations: bool = True) -> dict:
    """
    Run puzzle solver on analyzed data.

    Args:
        temp_folder_name: Name of analysis folder (e.g., 'analysis_20251120_100049')
                         If None, uses most recent analysis
        piece_id_1: First piece ID for comparison (optional)
        piece_id_2: Second piece ID for comparison (optional)
        solver_algorithm: Algorithm to use ('matrix', 'edge', 'edge_v2')
        show_visualizations: Whether to display visualizations

    Returns:
        dict: Solver results
    """
    results = solve_puzzle(
        temp_folder_name=temp_folder_name,
        piece_id_1=piece_id_1,
        piece_id_2=piece_id_2,
        solver_algorithm=solver_algorithm,
        show_visualizations=show_visualizations
    )

    # Always show the final assembly result at the end (regardless of show_visualizations)
    if results is not None and solver_algorithm == 'edge_v2':
        # Determine the temp folder path
        if temp_folder_name:
            assembly_image_path = Path(__file__).parent / 'temp' / temp_folder_name / 'assembly_steps_combined.png'
        else:
            # Find the most recent analysis folder
            temp_base = Path(__file__).parent / 'temp'
            analysis_folders = sorted(temp_base.glob('analysis_*'))
            if analysis_folders:
                assembly_image_path = analysis_folders[-1] / 'assembly_steps_combined.png'
            else:
                assembly_image_path = None

        if assembly_image_path and assembly_image_path.exists():
            print(f"\n{'='*70}")
            print("FINAL ASSEMBLY RESULT")
            print(f"{'='*70}")
            print(f"Loading final assembly visualization from: {assembly_image_path}")

            final_assembly_img = cv2.imread(str(assembly_image_path))

            if final_assembly_img is not None:
                # Use interactive viewer for scrollable/zoomable display, starting at bottom with zoom out
                viewer = InteractiveImageViewer("Final Assembly Result - Zoom & Scroll")
                viewer.show(final_assembly_img, start_at_bottom=True, initial_zoom=0.6)
            else:
                print("Warning: Could not load assembly image")
        else:
            print(f"\nNote: Assembly visualization not found")

    return results


if __name__ == "__main__":
    # Solve the puzzle using the most recent SVG analysis
    # Uses data from temp/analysis_TIMESTAMP/ directory generated by puzzle_analyzer

    # Option 1: Use most recent analysis folder automatically
    # run_solver()

    # Option 2: Specify a specific analysis folder
    # run_solver(temp_folder_name='analysis_20251118_085130')

    # Option 3: Compare specific pieces
    # run_solver(piece_id_1=0, piece_id_2=1)

    # Option 4: Specify both folder and pieces
    # array_files = ['analysis_20251118_103939', 'analysis_20251118_103945','analysis_20251118_103955']
    # run_solver(temp_folder_name=array_files[2], piece_id_1=0, piece_id_2=1)

    # Option 5: Full control - specify algorithm, folder, and pieces
    array_files = ['analysis_20251120_100049', 'analysis_20251120_100144','analysis_20251121_125023']
    run_solver(
        temp_folder_name=array_files[0],
        piece_id_1=1,
        piece_id_2=3,
        solver_algorithm='edge_v2',
        show_visualizations=False
    )
