"""Load and parse puzzle analysis data from SVG files."""
from pathlib import Path
from dataclasses import dataclass
from typing import List, Tuple
from .svg_data_loader import SVGDataLoader
from ..common.data_classes import Point, Corner, Segment


@dataclass
class AnalyzedPuzzlePiece:
    piece_id: int
    area: float
    centroid: Point
    contour_points: List[Point]
    outer_corners: List[Corner]
    inner_corners: List[Corner]
    frame_corners: List[Corner]
    segments: List[Segment]

    @property
    def has_frame_corner(self) -> bool:
        return len(self.frame_corners) > 0


@dataclass
class PuzzleAnalysisData:
    timestamp: str
    image_path: str
    pieces: List[AnalyzedPuzzlePiece]


class PuzzleDataLoader:
    """Loads puzzle analysis data from SVG files generated by puzzle_analyzer_v2."""

    @staticmethod
    def load_from_temp_folder(temp_folder: Path) -> PuzzleAnalysisData:
        """
        Load puzzle analysis from SVG file in analysis folder.

        Args:
            temp_folder: Path to temp directory or specific analysis folder

        Returns:
            PuzzleAnalysisData object with pieces loaded from SVG
        """
        # Find the latest analysis folder if temp_folder is the temp directory
        if temp_folder.name.startswith('analysis_'):
            latest_folder = temp_folder
        else:
            # Look for analysis_* folders (new format from puzzle_analyzer_v2)
            analysis_folders = sorted(temp_folder.glob('analysis_*'))
            if not analysis_folders:
                raise FileNotFoundError(
                    f"No analysis folders found in {temp_folder}. "
                    f"Please run puzzle_analyzer_v2 first to generate analysis data."
                )
            latest_folder = analysis_folders[-1]

        # Load from SVG file
        svg_path = latest_folder / 'pieces_with_corners_without_helpers.svg'

        if not svg_path.exists():
            raise FileNotFoundError(
                f"SVG file not found: {svg_path}. "
                f"Please ensure puzzle_analyzer_v2 generated the SVG files."
            )

        print(f"Loading: {latest_folder.name}")

        # Parse SVG data
        svg_data = SVGDataLoader.load_from_svg(svg_path)

        # Convert to dataclass format
        def _parse_corners(c_list: List, c_type: str) -> List[Corner]:
            return [Corner(c['x'], c['y'], c_type) for c in c_list]

        def _parse_segments(seg_list: List) -> List[Segment]:
            return [
                Segment(
                    id=seg['id'],
                    corner_start=Point(seg['corner_start']['x'], seg['corner_start']['y']),
                    corner_end=Point(seg['corner_end']['x'], seg['corner_end']['y']),
                    is_straight=seg['is_straight']
                )
                for seg in seg_list
            ]

        pieces = []
        for pd in svg_data['pieces']:
            piece = AnalyzedPuzzlePiece(
                piece_id=pd['piece_id'],
                area=pd['area'],
                centroid=Point(pd['centroid']['x'], pd['centroid']['y']),
                contour_points=[Point(p['x'], p['y']) for p in pd['contour_points']],
                outer_corners=_parse_corners(pd['outer_corners'], 'outer'),
                inner_corners=_parse_corners(pd['inner_corners'], 'inner'),
                frame_corners=_parse_corners(pd['frame_corners'], 'frame'),
                segments=_parse_segments(pd['segments'])
            )
            pieces.append(piece)

        # Get image path from the analysis folder (look for the original image reference)
        # For now, use a placeholder - we can enhance this later if needed
        image_path = "images/puzzle.jpg"  # Default path
        timestamp = latest_folder.name.replace('analysis_', '')

        return PuzzleAnalysisData(timestamp, image_path, pieces)


def print_analysis_summary(data: PuzzleAnalysisData) -> None:
    """Print summary of loaded analysis data."""
    print(f"\n{'='*60}")
    print(f"PUZZLE ANALYSIS - {data.timestamp}")
    print(f"Image: {data.image_path}")
    print(f"Pieces: {len(data.pieces)}")
    for p in data.pieces:
        corners = f"({len(p.frame_corners)} frame)" if p.has_frame_corner else "(interior)"
        print(f"  P{p.piece_id}: {p.area:.0f}px² | Corners: {corners}")
    print(f"{'='*60}\n")

