"""Load and parse puzzle analysis data from SVG files."""
import xml.etree.ElementTree as ET
import re
import numpy as np
from pathlib import Path
from typing import List, Tuple, Dict


class SVGDataLoader:
    """Loads puzzle analysis data from SVG files generated by puzzle_analyzer_v2."""

    @staticmethod
    def load_from_svg(svg_path: Path) -> Dict:
        """
        Load puzzle analysis data from SVG file with embedded corner data.

        Args:
            svg_path: Path to pieces_with_corners_without_helpers.svg file

        Returns:
            Dict with keys:
                - 'pieces': List of piece data dicts
                - 'image_width': SVG width
                - 'image_height': SVG height
        """
        print(f"Loading SVG data from: {svg_path}")

        # Parse SVG
        tree = ET.parse(svg_path)
        root = tree.getroot()

        # Get SVG dimensions
        svg_width = int(root.get('width', 0))
        svg_height = int(root.get('height', 0))

        # Find all path elements with piece data
        # SVG has both filled and unfilled paths with different piece IDs but sometimes same geometry
        # We need to deduplicate by path 'd' attribute
        namespace = {'svg': 'http://www.w3.org/2000/svg'}
        all_paths = root.findall('.//svg:path', namespace)
        if not all_paths:
            all_paths = root.findall('.//path')

        # Filter to paths with piece-id and segments data
        paths_with_data = [p for p in all_paths if p.get('data-piece-id') is not None and p.get('data-segments') is not None]

        # Deduplicate by outer-corners attribute (more reliable than path 'd')
        # SVG has duplicate paths with same 'd' but different corner data
        seen_corners = {}
        paths = []
        for p in paths_with_data:
            corners_str = p.get('data-outer-corners', '')
            if corners_str and corners_str not in seen_corners:
                seen_corners[corners_str] = True
                paths.append(p)

        pieces_data = []

        for path_elem in paths:
            piece_id = int(path_elem.get('data-piece-id'))
            path_d = path_elem.get('d', '')

            # Parse corners from data attributes
            outer_corners = SVGDataLoader._parse_corner_string(path_elem.get('data-outer-corners', ''))
            inner_corners = SVGDataLoader._parse_corner_string(path_elem.get('data-inner-corners', ''))
            frame_corners = SVGDataLoader._parse_corner_string(path_elem.get('data-frame-corners', ''))

            # Parse segments from data attributes
            segments = SVGDataLoader._parse_segments_string(path_elem.get('data-segments', ''))

            # Extract contour points from SVG path
            contour_points = SVGDataLoader._parse_svg_path(path_d)

            # Calculate centroid and area from contour
            if len(contour_points) > 0:
                contour_array = np.array(contour_points, dtype=np.float32).reshape(-1, 1, 2)

                # Calculate moments for centroid
                import cv2
                moments = cv2.moments(contour_array)
                if moments['m00'] != 0:
                    centroid_x = moments['m10'] / moments['m00']
                    centroid_y = moments['m01'] / moments['m00']
                else:
                    centroid_x = np.mean([p[0] for p in contour_points])
                    centroid_y = np.mean([p[1] for p in contour_points])

                area = cv2.contourArea(contour_array)
            else:
                centroid_x, centroid_y = 0.0, 0.0
                area = 0.0

            piece_data = {
                'piece_id': piece_id,
                'area': area,
                'centroid': {'x': centroid_x, 'y': centroid_y},
                'contour_points': [{'x': p[0], 'y': p[1]} for p in contour_points],
                'outer_corners': [{'x': c[0], 'y': c[1]} for c in outer_corners],
                'inner_corners': [{'x': c[0], 'y': c[1]} for c in inner_corners],
                'frame_corners': [{'x': c[0], 'y': c[1]} for c in frame_corners],
                'segments': segments
            }

            pieces_data.append(piece_data)

        print(f"  Loaded {len(pieces_data)} pieces from SVG")

        return {
            'pieces': pieces_data,
            'image_width': svg_width,
            'image_height': svg_height
        }

    @staticmethod
    def _parse_corner_string(corner_str: str) -> List[Tuple[float, float]]:
        """
        Parse corner string from SVG data attribute.

        Args:
            corner_str: String like "675,714;599,747;631,831"

        Returns:
            List of (x, y) tuples
        """
        if not corner_str:
            return []

        corners = []
        for coord_pair in corner_str.split(';'):
            coord_pair = coord_pair.strip()
            if coord_pair:
                parts = coord_pair.split(',')
                if len(parts) == 2:
                    x = float(parts[0])
                    y = float(parts[1])
                    corners.append((x, y))

        return corners

    @staticmethod
    def _parse_segments_string(segments_str: str) -> List[Dict]:
        """
        Parse segments string from SVG data attribute.

        Args:
            segments_str: String like "0:675,714-599,747:1;1:599,747-631,831:0"
                         Format: id:x1,y1-x2,y2:is_straight

        Returns:
            List of segment dicts with keys: id, corner_start, corner_end, is_straight
        """
        if not segments_str:
            return []

        segments = []
        for seg_str in segments_str.split(';'):
            seg_str = seg_str.strip()
            if seg_str:
                # Parse format: "id:x1,y1-x2,y2:is_straight"
                parts = seg_str.split(':')
                if len(parts) == 3:
                    seg_id = int(parts[0])
                    coords = parts[1]
                    is_straight = bool(int(parts[2]))

                    # Parse coordinates
                    coord_parts = coords.split('-')
                    if len(coord_parts) == 2:
                        start_coords = coord_parts[0].split(',')
                        end_coords = coord_parts[1].split(',')

                        if len(start_coords) == 2 and len(end_coords) == 2:
                            corner_start = {
                                'x': float(start_coords[0]),
                                'y': float(start_coords[1])
                            }
                            corner_end = {
                                'x': float(end_coords[0]),
                                'y': float(end_coords[1])
                            }

                            segments.append({
                                'id': seg_id,
                                'corner_start': corner_start,
                                'corner_end': corner_end,
                                'is_straight': is_straight
                            })

        return segments

    @staticmethod
    def _parse_svg_path(path_d: str) -> List[Tuple[float, float]]:
        """
        Parse SVG path 'd' attribute to extract contour points.

        Args:
            path_d: SVG path data string (e.g., "M 671.00,714.00 L 599.00,747.00 ...")

        Returns:
            List of (x, y) coordinate tuples
        """
        if not path_d:
            return []

        points = []

        # Simple parser for M (move) and L (line) commands
        # Remove 'Z' (close path) command
        path_d = path_d.replace('Z', '').strip()

        # Split by command letters
        commands = re.split(r'([ML])', path_d)
        commands = [c.strip() for c in commands if c.strip()]

        i = 0
        while i < len(commands):
            cmd = commands[i]
            if cmd in ['M', 'L'] and i + 1 < len(commands):
                # Next element should be coordinates
                coords_str = commands[i + 1]
                # Parse coordinate pairs (can be space or comma separated)
                coord_pairs = coords_str.replace(',', ' ').split()

                # Group into x,y pairs
                j = 0
                while j + 1 < len(coord_pairs):
                    try:
                        x = float(coord_pairs[j])
                        y = float(coord_pairs[j + 1])
                        points.append((x, y))
                        j += 2
                    except (ValueError, IndexError):
                        j += 1

                i += 2
            else:
                i += 1

        return points
